name: FirstPlugin
version: 1.0
main: org.example.Main
api-version: '26.1.2'

commands:
  bacchetta:
    description: Explosion batoon
    usage: /bacchetta
  reassembly:
    description: Seq 1 reassembly
    usage: /reassembly